name: githubjobs
description: a list of github jobs

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  get_it: ^4.0.1
  json_annotation: ^3.0.1
  logger: ^0.9.1
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.6+3
  connectivity: ^2.0.2
  http: ^0.12.2
  cached_network_image: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.5
  build_runner: ^1.11.0
  mockito: ^4.1.1
  environment_config: ^2.2.5

flutter:
  uses-material-design: true
  assets:
    - assets/img/
